### ISSUE TITLE
Problem with characters overlay

### ISSUE THREAD

**Issue by 8eS3rz4sDu8oUx4q39hhv8o2k2e72dkb** [nongthaihoang/android_san_francisco_font#1]
Hello. I have an issue with overlaying symbols in first sentences over all OS in Android 9, especially on web pages.
**SanFrancisco_Fonts_w_emoji_By_Apple.Inc-v4.0.zip ➡️ SF Fonts Magisk w/ Emoji (Magisk)** version is installed.

After I disable module in Magisk, everything is fine. And No, this is **not** my Web Browser problem(I use Opera)

Screenshots before and after below:
![Disabled](https://user-images.githubusercontent.com/41873741/71364981-b6d26380-25ae-11ea-9724-33224421aba8.jpg)
![Enabled](https://user-images.githubusercontent.com/41873741/71364982-b6d26380-25ae-11ea-9b91-ed2163b4f96b.jpg)

**Comment by nongthaihoang** [comment]
That is not mine. You've must be mistaken. Please download the zip from here:
https://github.com/nongthaihoang/android_san_francisco_font/releases
