### ISSUE TITLE
I discovered a really beautiful rounded SF font, can you make it flashable in Magisk?

### ISSUE THREAD

**Issue by tuhuynh23** [nongthaihoang/android_san_francisco_font#2]
Here link to the font in my GDrive:
https://drive.google.com/file/d/1ieV8bP20XXRvFnfWM2jrGGZkVlVXE9bu/view?usp=sharing

**Comment by tuhuynh23** [comment]
Oh and really thank for your time

**Comment by tuhuynh23** [comment]
I use your module as a template and made a new one with that font. It have some render isssue but enough to be daily driver. Here is the link:
https://drive.google.com/open?id=1dfrY2hN4IFDKDJ23lhSKCNKTmJDk-Jj8

**Comment by nongthaihoang** [comment]
Thanks for suggestions. I'm aware of the existence of the rounded SF. That's where I got the rounded style from.
There is a folder named /custom/rd. Put all the rounded font files you have into that folder without replacing the existing one. And you're good to go.
